name: free-money
favicon: null
layout_spectrum: 0.38599777151830494
typography_spectrum: 0.4285900183022022
title: Free bitcoin faucets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5634665556717664
  lightness: 0.3252181285060942
  saturation: 0.7016269299201667
  rhythmicContrast: 0.1967394209932536
purpose: []
